# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='org',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orgs.Org'),
        ),
    ]
